apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: data-script
  name: data-script
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: data-script
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: data-script
    spec:
      containers:
      - env:
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: MYSQL_ALLOW_EMPTY_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: MYSQL_DATABASE
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: MYSQL_PASSWORD
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: MYSQL_ROOT_PASSWORD
        image: sulaimanovm/quotes-data-script:v1
        name: data-script
        resources: {}
      restartPolicy: Always
status: {}
