version: "3"
services:

  front:
    container_name: front
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - myapp

  back:
    container_name: api
    build:
      context: back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - myapp

  data:
    container_name: db
    build:
      context: data
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "mydatabase"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - myapp

  data-script:
    container_name: data-script
    build:
      context: data-script
      dockerfile: Dockerfile
    networks:
      - myapp

networks:
  myapp:
