apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  login: U1FMQUxDSEVNWV9EQVRBQkFTRV9VUkk=
  password: bXlzcWwrcHlteXNxbDovL3Jvb3Q6cm9vdEBkYXRhOjMzMDYvbXlkYXRhYmFzZQ==
  MYSQL_ALLOW_EMPTY_PASSWORD: InllcyI=
  MYSQL_DATABASE: bXlkYXRhYmFzZQ==
  MYSQL_PASSWORD: cm9vdA==
  MYSQL_ROOT_PASSWORD: cm9vdA==